import { Customer, PortalUser, Invoice } from './types';

export const MASTER_CHECKLIST: Record<string, string[]> = {
  'HVAC & Air Quality': [
    'Provide and replace HVAC filter',
    'Clean HVAC condensate line',
    'Check thermostat operation',
    'Inspect visible ductwork',
  ],
  'Plumbing': [
    'Inspect plumbing under all sinks',
    'Inspect toilets for leaks',
    'Inspect outdoor faucets',
    'Inspect interior faucets',
    'Inspect all drains',
    'Clean garbage disposal',
  ],
  'Electrical & Safety': [
    'Check smoke detector batteries',
    'Test smoke detectors',
    'Test CO detectors',
    'Check light bulbs',
    'Check GFCI outlets',
    'Inspect panel',
  ],
  'Appliances': [
    'Clean dryer vent hose',
    'Clean refrigerator coils',
    'Replace refrigerator water filter',
    'Inspect dishwasher filter',
    'Check appliance operation',
  ],
  'Exterior & Structure': [
    'Visual exterior inspection',
    'Inspect rain gutters',
    'Check windows',
    'Check exterior doors',
    'Seal windows/doors for drafts',
    'Inspect roof from ground',
  ],
  'Interior & General': [
    'Minor door adjustments',
    'Caulk shower/tub',
    'Small drywall repair',
    'Inspect garage door',
    'Check flooring condition',
    'Inspect ceiling for stains',
  ],
  'Pest & Landscaping': [
    'Check for pest activity',
    'Vegetation touching structure',
    'Drainage/standing water',
    'Tree limbs over roof',
    'Lawn/landscape condition',
  ],
};

export const DEFAULT_ROOMS = ['Exterior / Yard', 'Whole-House Systems', 'Kitchen', 'Living Room / Family Room', 'Hallways / Entry Areas', 'Primary Bedroom', 'Primary Bathroom', 'Bedroom 2', 'Bathroom 2', 'Laundry Room', 'Garage'];

export const COMMON_ROOMS = ['Exterior / Yard', 'Whole-House Systems', 'Hallways / Entry Areas', 'Kitchen', 'Living Room / Family Room', 'Living Room', 'Family Room', 'Primary Bedroom', 'Primary Bathroom', 'Bedroom 2', 'Bedroom 3', 'Bedroom 4', 'Bathroom 2', 'Bathroom 3', 'Half Bathroom', 'Powder Room', 'Dining Room', 'Office', 'Laundry Room', 'Garage', 'Basement', 'Crawlspace', 'Attic', 'Mechanical Room', 'Utility Room', 'Electrical Panel', 'Deck / Patio', 'Sunroom', 'Pool House'];

export const VENDOR_ICONS: Record<string, string> = {
  'HVAC': '❄️',
  'Pest Control': '🐛',
  'Landscape/Lawn': '🌿',
  'Electrician': '⚡',
  'Plumber': '🔧',
  'Roofing': '🏠',
  'Painter': '🎨',
  'Appliance Repair': '🫧',
  'Security/Alarm': '🔒',
  'Locksmith': '🔑',
  'Cleaning Service': '🧼',
  'Pressure Washing': '💦',
  'Pool Service': '🏊',
  'Other': '📋',
};

export const VENDOR_TYPES = Object.keys(VENDOR_ICONS) as string[];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'c1',
    name: '142 Oakwood Drive',
    address: '142 Oakwood Drive, Nashville, TN 37205',
    owner: 'James & Linda Hartwell',
    phone: '(615) 555-0182',
    email: 'jhartwell@email.com',
    plan: 'Monthly $85/mo',
    home: {
      sqft: '2,850',
      yearBuilt: '1998',
      stories: '2',
      garage: '2-car attached',
      pool: false,
      roofType: 'Asphalt Shingles',
      roofAge: '8 years',
      hvacType: 'Central Air/Gas Heat',
      hvacAge: '5 years',
      notes: 'Key lockbox code: 4821. Dog named Biscuit — very friendly. Owners prefer visits on Tuesday mornings.',
    },
    vendors: [
      { id: 'v1', type: 'HVAC', company: 'Cool Breeze HVAC', phone: '(615) 555-0210', account: 'CB-10482', notes: 'Preferred tech: Mike D.' },
      { id: 'v2', type: 'Pest Control', company: 'Shield Pest Solutions', phone: '(615) 555-0334', account: 'SPS-2291', notes: 'Quarterly treatment plan' },
      { id: 'v3', type: 'Plumber', company: 'Nashville Flow Plumbing', phone: '(615) 555-0471', account: 'NF-882', notes: 'Emergency line available 24/7' },
    ],
    rooms: ['Exterior', 'Living Room', 'Kitchen', 'Master Bedroom', 'Master Bathroom', 'Garage'],
    checklist: {
      'Exterior': ['Visual exterior inspection', 'Inspect rain gutters', 'Check windows', 'Check exterior doors', 'Inspect roof from ground', 'Check for pest activity', 'Tree limbs over roof'],
      'Living Room': ['Check smoke detector batteries', 'Test smoke detectors', 'Check light bulbs', 'Check flooring condition', 'Inspect ceiling for stains'],
      'Kitchen': ['Inspect plumbing under all sinks', 'Inspect all drains', 'Clean garbage disposal', 'Clean refrigerator coils', 'Replace refrigerator water filter', 'Inspect dishwasher filter', 'Check appliance operation', 'Check GFCI outlets'],
      'Master Bedroom': ['Check smoke detector batteries', 'Test smoke detectors', 'Minor door adjustments', 'Check flooring condition'],
      'Master Bathroom': ['Inspect plumbing under all sinks', 'Inspect toilets for leaks', 'Inspect interior faucets', 'Inspect all drains', 'Caulk shower/tub', 'Check GFCI outlets'],
      'Garage': ['Inspect garage door', 'Check smoke detector batteries', 'Inspect panel', 'Clean dryer vent hose'],
    },
    findings: {
      'Kitchen': [
        {
          id: 'f1',
          itemKey: 'Inspect plumbing under all sinks',
          title: 'Inspect plumbing under all sinks',
          room: 'Kitchen',
          status: 'Needs Repair',
          priority: 'High',
          description: 'Slow drip from P-trap connection under kitchen sink. Water staining visible on cabinet floor.',
          action: 'Replace P-trap and inspect supply lines',
          due: 'June 1, 2026',
          quoteStatus: 'Ready to Quote',
        },
      ],
      'Exterior': [
        {
          id: 'f2',
          itemKey: 'Inspect rain gutters',
          title: 'Inspect rain gutters',
          room: 'Exterior',
          status: 'Monitor',
          priority: 'Medium',
          description: 'Rear gutters have minor debris buildup. Downspout on north side slightly loose at bracket.',
          action: 'Clean gutters and re-secure downspout bracket',
          due: 'May 30, 2026',
          quoteStatus: 'Not Sent',
        },
      ],
    },
    photos: {},
    requests: [
      {
        id: 'req1',
        customerId: 'c1',
        customerName: 'James & Linda Hartwell',
        category: 'Plumbing',
        room: 'Kitchen',
        description: 'The kitchen faucet has been dripping slowly even when fully turned off. Been going on for about a week.',
        priority: 'Medium',
        status: 'Scheduled',
        contractorNotes: 'Scheduled for next Tuesday visit. Will replace cartridge.',
        submittedAt: 'May 2, 2026',
        read: true,
      },
      {
        id: 'req2',
        customerId: 'c1',
        customerName: 'James & Linda Hartwell',
        category: 'HVAC',
        room: 'Upstairs hallway',
        description: 'The upstairs is staying about 5 degrees warmer than the thermostat setting. Filter was changed last month.',
        priority: 'Low',
        status: 'Pending',
        contractorNotes: '',
        submittedAt: 'May 6, 2026',
        read: false,
      },
    ],
    lastVisit: 'April 18, 2026',
    invoices: [],
    reportLogs: [],
    isActive: true,
  },
  {
    id: 'c2',
    name: '78 Maple Ridge Ct',
    address: '78 Maple Ridge Ct, Brentwood, TN 37027',
    owner: 'Sandra Okafor',
    phone: '(615) 555-0294',
    email: 'sokafor@promail.com',
    plan: 'Quarterly $240',
    home: {
      sqft: '3,400',
      yearBuilt: '2005',
      stories: '2',
      garage: '3-car attached',
      pool: true,
      roofType: 'Tile',
      roofAge: '12 years',
      hvacType: 'Heat Pump',
      hvacAge: '3 years',
      notes: 'Gate code: 7742. No pets. Owner travels frequently — send report summary via email.',
    },
    vendors: [
      { id: 'v4', type: 'HVAC', company: 'Total Comfort Systems', phone: '(615) 555-0150', account: 'TCS-5503', notes: 'Annual service contract active' },
      { id: 'v5', type: 'Pool Service', company: 'AquaBlue Pool Care', phone: '(615) 555-0388', account: 'AB-771', notes: 'Weekly service, chemical log on file' },
      { id: 'v6', type: 'Landscape/Lawn', company: 'GreenEdge Landscaping', phone: '(615) 555-0422', account: 'GE-1149', notes: 'Bi-weekly mowing, monthly edging' },
      { id: 'v7', type: 'Security/Alarm', company: 'SafeGuard Home Security', phone: '(615) 555-0509', account: 'SG-3304', notes: 'Monitoring plan: Premium 24/7' },
    ],
    rooms: ['Exterior', 'Living Room', 'Kitchen', 'Master Bedroom', 'Master Bathroom', 'Garage'],
    checklist: {
      'Exterior': ['Visual exterior inspection', 'Inspect rain gutters', 'Check windows', 'Check exterior doors', 'Inspect roof from ground', 'Check for pest activity', 'Vegetation touching structure', 'Drainage/standing water'],
      'Living Room': ['Check smoke detector batteries', 'Test smoke detectors', 'Test CO detectors', 'Check light bulbs', 'Check flooring condition'],
      'Kitchen': ['Inspect plumbing under all sinks', 'Clean garbage disposal', 'Check appliance operation', 'Check GFCI outlets'],
      'Master Bedroom': ['Check smoke detector batteries', 'Minor door adjustments', 'Check flooring condition', 'Inspect ceiling for stains'],
      'Master Bathroom': ['Inspect plumbing under all sinks', 'Inspect toilets for leaks', 'Caulk shower/tub', 'Check GFCI outlets'],
      'Garage': ['Inspect garage door', 'Inspect panel', 'Clean dryer vent hose'],
    },
    findings: {
      'Master Bathroom': [
        {
          id: 'f3',
          itemKey: 'Caulk shower/tub',
          title: 'Caulk shower/tub',
          room: 'Master Bathroom',
          status: 'Urgent',
          priority: 'Urgent',
          description: 'Caulk around master shower pan completely failed — gap visible, mold growth starting at base. Risk of water intrusion into subfloor.',
          action: 'Remove old caulk, treat mold, re-caulk immediately',
          due: 'May 15, 2026',
          quoteStatus: 'Approved',
        },
      ],
    },
    photos: {},
    requests: [
      {
        id: 'req3',
        customerId: 'c2',
        customerName: 'Sandra Okafor',
        category: 'Exterior',
        room: 'Back yard',
        description: 'There is a section of fence near the pool that looks like it\'s leaning. One of the posts may be rotting at the base.',
        priority: 'Medium',
        status: 'In Progress',
        contractorNotes: 'Inspected — post is rotted. Getting quote from fencing contractor.',
        submittedAt: 'April 28, 2026',
        read: true,
      },
      {
        id: 'req4',
        customerId: 'c2',
        customerName: 'Sandra Okafor',
        category: 'Pest/Landscaping',
        room: 'Garage',
        description: 'Noticed what looks like ant trails along the garage baseboard near the water heater. Want it checked before it gets worse.',
        priority: 'Urgent',
        status: 'Completed',
        contractorNotes: 'Pest control called. Treated perimeter and interior. Follow-up in 30 days.',
        submittedAt: 'April 15, 2026',
        read: true,
      },
      {
        id: 'req5',
        customerId: 'c2',
        customerName: 'Sandra Okafor',
        category: 'Interior',
        room: 'Master Bathroom',
        description: 'Small water stain appearing on the ceiling below the master bath. Seems to be getting slightly larger.',
        priority: 'Urgent',
        status: 'Pending',
        contractorNotes: '',
        submittedAt: 'May 7, 2026',
        read: false,
      },
    ],
    lastVisit: 'April 10, 2026',
    qbCustomerId: 'QB-CUST-8821',
    invoices: [
      {
        id: 'inv1',
        invoiceNumber: 'INV-2026-001',
        customerId: 'c2',
        date: 'March 15, 2026',
        dueDate: 'April 14, 2026',
        lineItems: [
          { id: 'li1', description: 'Caulk shower/tub — Master Bathroom', category: 'Interior', quantity: 1, rate: 125, amount: 125 },
          { id: 'li2', description: 'Gutter cleaning and downspout reattachment', category: 'Exterior', quantity: 1, rate: 60, amount: 60 },
        ],
        taxRate: 0,
        notes: 'Thank you for your continued service plan membership.',
        status: 'Paid',
      },
      {
        id: 'inv2',
        invoiceNumber: 'INV-2026-002',
        customerId: 'c2',
        date: 'May 1, 2026',
        dueDate: 'May 31, 2026',
        lineItems: [
          { id: 'li3', description: 'Fence post replacement — Back yard', category: 'Exterior', quantity: 1, rate: 195, amount: 195 },
          { id: 'li4', description: 'Pest treatment follow-up inspection', category: 'Pest/Landscaping', quantity: 1, rate: 45, amount: 45 },
        ],
        taxRate: 0,
        notes: '',
        status: 'Sent',
      },
    ] as Invoice[],
  },
];

export const PORTAL_USER: PortalUser = {
  id: 'pu1',
  name: 'Sandra Okafor',
  email: 'sokafor@promail.com',
  customerId: 'c2',
};

export const PORTAL_DEMO_PASSWORD = 'demo1234';

export const SAMPLE_PORTAL_REPORTS = [
  {
    id: 'rpt1',
    date: 'April 10, 2026',
    property: '78 Maple Ridge Ct',
    findingsCount: 1,
    urgentCount: 1,
    status: 'Urgent' as const,
  },
  {
    id: 'rpt2',
    date: 'January 8, 2026',
    property: '78 Maple Ridge Ct',
    findingsCount: 3,
    urgentCount: 0,
    status: 'Issues' as const,
  },
];
