import {
  closeSync,
  constants,
  existsSync,
  fstatSync,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  readdirSync,
  realpathSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import {
  GENESIS_HASH,
  EvidenceError,
  assertCanonicalParents,
  assertOutsideGit,
  canonicalStringify,
  fsyncDirectory,
  sha256File,
  validateRawOperationRootInput,
} from './internal.mjs';
import { BROWSER_LIMITS, BROWSER_PROVENANCE_MODES, buildBrowserRecord, computeBrowserRunAuthTag, decodeUtf8, parseBrowserJournal } from './browser-schema.mjs';

export const JOURNAL_FILENAME = 'browser-journal.ndjson';

function modeOf(info) {
  return info.mode & 0o777;
}

export function validateJournalRootInput(root) {
  validateRawOperationRootInput(root, 'browser journal root');
  const rootPath = resolve(root);
  assertCanonicalParents(rootPath);
  assertOutsideGit(dirname(rootPath));
  if (!existsSync(rootPath)) mkdirSync(rootPath, { mode: 0o700 });
  const real = realpathSync(rootPath);
  if (real !== rootPath) throw new EvidenceError('SYMLINK_REJECTED', 'Browser journal root must not use symlinked path components.');
  const info = lstatSync(rootPath);
  if (!info.isDirectory() || info.isSymbolicLink() || info.uid !== process.getuid?.() || modeOf(info) !== 0o700) {
    throw new EvidenceError('UNSAFE_BROWSER_JOURNAL_ROOT', 'Browser journal root ownership, type, or mode is unsafe.');
  }
  return rootPath;
}

export function assertJournalFile(path, { maximumBytes = BROWSER_LIMITS.journal_bytes } = {}) {
  const info = lstatSync(path);
  if (!info.isFile() || info.isSymbolicLink() || info.uid !== process.getuid?.() || info.nlink !== 1 || modeOf(info) !== 0o600) {
    throw new EvidenceError('UNSAFE_BROWSER_JOURNAL', 'Browser journal ownership, type, link count, or mode is unsafe.');
  }
  if (info.size > maximumBytes) throw new EvidenceError('BROWSER_JOURNAL_LIMIT', 'Browser journal exceeds its byte limit.');
  return info;
}

export function assertExactlyOneJournal(root, expectedPath = null) {
  const entries = readdirSync(root).sort();
  if (entries.length !== 1 || entries[0] !== JOURNAL_FILENAME) throw new EvidenceError('UNKNOWN_BROWSER_JOURNAL_FILE', 'Browser journal root must contain exactly one known journal file.');
  const journalPath = join(root, JOURNAL_FILENAME);
  if (expectedPath && resolve(expectedPath) !== journalPath) throw new EvidenceError('BROWSER_JOURNAL_MISMATCH', 'Browser journal path is not the expected journal.');
  return journalPath;
}

export function createJournalWriter(root, { journalAuthSecret = null, allowPrepared = false, provenanceMode = null } = {}) {
  const rootPath = validateJournalRootInput(root);
  const mode = provenanceMode ?? (journalAuthSecret ? 'generated_workspace' : 'standalone');
  if (!BROWSER_PROVENANCE_MODES.includes(mode)) throw new EvidenceError('INVALID_BROWSER_PROVENANCE_MODE', 'Browser journal provenance mode is invalid.');
  if (!journalAuthSecret) throw new EvidenceError('INVALID_BROWSER_AUTH_SECRET', 'Browser journal writer requires an authenticated session secret.');
  const journalPath = join(rootPath, JOURNAL_FILENAME);
  let descriptor;
  if (existsSync(journalPath)) {
    if (!allowPrepared) throw new EvidenceError('PREEXISTING_BROWSER_JOURNAL', 'Browser journal already exists.');
    const prepared = assertJournalFile(journalPath);
    if (prepared.size !== 0) throw new EvidenceError('PREEXISTING_BROWSER_JOURNAL', 'Prepared browser journal is not empty.');
    descriptor = openSync(journalPath, constants.O_WRONLY | constants.O_NOFOLLOW, 0o600);
  } else {
    descriptor = openSync(journalPath, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600);
  }
  const info = fstatSync(descriptor);
  if (!info.isFile() || info.uid !== process.getuid?.() || info.nlink !== 1 || modeOf(info) !== 0o600) {
    closeSync(descriptor);
    try { unlinkSync(journalPath); } catch {}
    throw new EvidenceError('UNSAFE_BROWSER_JOURNAL', 'Created browser journal failed ownership checks.');
  }

  let sequence = 0;
  let previousHash = GENESIS_HASH;
  let bytes = 0;
  let closed = false;
  let terminalWritten = false;

  const append = (input) => {
    if (closed) throw new EvidenceError('BROWSER_JOURNAL_CLOSED', 'Browser journal is already closed.');
    if (terminalWritten) throw new EvidenceError('BROWSER_JOURNAL_TERMINAL', 'Browser journal already has a terminal record.');
    if (input.run_auth_tag !== undefined && input.run_auth_tag !== null) {
      throw new EvidenceError('INVALID_BROWSER_AUTH_TAG', 'Browser journal terminal auth tags are generated by the harness.');
    }
    sequence += 1;
    if (sequence > BROWSER_LIMITS.journal_records) throw new EvidenceError('BROWSER_RECORD_LIMIT', 'Browser journal record limit exceeded.');
    const recordInput = { ...input, sequence, provenance_mode: mode };
    if (recordInput.record_type === 'browser_run_completed' && !recordInput.run_auth_tag) {
      const authCandidate = {
        schema_version: 'servsync-controlled-ops/browser-journal-v1',
        sequence: recordInput.sequence,
        record_type: recordInput.record_type,
        run_id: recordInput.run_id,
        provenance_mode: recordInput.provenance_mode,
        timestamp: recordInput.timestamp,
        target_classification: 'local',
        project: 'chromium',
        worker_index: recordInput.worker_index ?? null,
        retry_index: recordInput.retry_index ?? null,
        spec_path: recordInput.spec_path ?? null,
        test_id: recordInput.test_id ?? null,
        attempt_id: recordInput.attempt_id ?? null,
        safe_label: recordInput.safe_label ?? null,
        status: recordInput.status ?? null,
        duration_ms: recordInput.duration_ms ?? null,
        error_classification: recordInput.error_classification ?? 'none',
        run_auth_tag: null,
        previous_record_hash: previousHash,
      };
      recordInput.run_auth_tag = computeBrowserRunAuthTag(journalAuthSecret, authCandidate);
    }
    const record = buildBrowserRecord(previousHash, recordInput);
    const line = `${canonicalStringify(record)}\n`;
    const lineBytes = Buffer.byteLength(line);
    if (lineBytes > BROWSER_LIMITS.line_bytes || bytes + lineBytes > BROWSER_LIMITS.journal_bytes) {
      throw new EvidenceError('BROWSER_JOURNAL_LIMIT', 'Browser journal byte limit exceeded.');
    }
    writeFileSync(descriptor, line, 'utf8');
    fsyncSync(descriptor);
    bytes += lineBytes;
    previousHash = record.current_record_hash;
    if (record.record_type === 'browser_run_completed') terminalWritten = true;
    return record;
  };

  const close = () => {
    if (closed) return;
    fsyncSync(descriptor);
    closeSync(descriptor);
    fsyncDirectory(rootPath);
    assertJournalFile(journalPath);
    closed = true;
  };

  return { rootPath, journalPath, append, close };
}

export function readJournal(journalPath) {
  const root = validateJournalRootInput(dirname(resolve(journalPath)));
  const expectedPath = assertExactlyOneJournal(root, resolve(journalPath));
  assertJournalFile(expectedPath);
  const before = statSync(expectedPath);
  const digestBefore = sha256File(expectedPath, BROWSER_LIMITS.journal_bytes);
  const buffer = readFileSync(expectedPath);
  const after = statSync(expectedPath);
  if (before.dev !== after.dev || before.ino !== after.ino || before.size !== after.size || before.mtimeMs !== after.mtimeMs) {
    throw new EvidenceError('BROWSER_JOURNAL_REPLACED', 'Browser journal changed while being read.');
  }
  const content = decodeUtf8(buffer);
  const parsed = parseBrowserJournal(content);
  const digestAfter = sha256File(expectedPath, BROWSER_LIMITS.journal_bytes);
  if (digestBefore !== digestAfter) throw new EvidenceError('BROWSER_JOURNAL_REPLACED', 'Browser journal digest changed during import.');
  return { path: expectedPath, sourceDigest: digestAfter, ...parsed };
}
