import type { DraftChecklistSourceOption } from './checklistDraftScope';

export type DraftChecklistStarterTemplate = DraftChecklistSourceOption & {
  id: string;
  name: string;
  kind: DraftChecklistSourceOption['workflow_kind'];
  trade: string;
  description: string;
};

const DEFAULT_INSPECTION_ROOMS = [
  { room: 'Exterior', items: [
    'Check exterior siding and trim for damage',
    'Check foundation for visible cracks or movement',
    'Check grading and drainage near the home',
    'Check exterior caulking, gaps, and penetrations',
    'Check decks, porches, steps, and trip hazards',
  ] },
  { room: 'Roof / Attic', items: [
    'Check visible roof covering condition',
    'Check flashing, vents, and roof penetrations',
    'Check gutters and downspouts for blockage or damage',
    'Check attic for moisture, staining, or ventilation concerns',
    'Check visible pest evidence where accessible',
  ] },
  { room: 'Mechanical / Safety', items: [
    'Check HVAC filter and visible airflow',
    'Check electrical panel for visible concerns',
    'Check GFCI protection where accessible',
    'Check smoke/CO detectors if accessible',
    'Check water heater area for leaks or corrosion',
  ] },
  { room: 'Kitchen', items: [
    'Check for active leaks under sinks',
    'Check sink, faucet, and drain operation',
    'Check cabinets, counters, and visible surfaces for damage',
    'Check major appliances for visible concerns',
    'Check kitchen GFCI protection where accessible',
  ] },
  { room: 'Living Room / Common Areas', items: [
    'Check walls, ceilings, and floors for visible damage',
    'Check doors and windows for operation',
    'Check outlets and switches for visible damage',
    'Check light fixtures and ceiling fans',
    'Check trip hazards or safety concerns',
  ] },
  { room: 'Dining Room', items: [
    'Check walls, ceilings, and floors for visible damage',
    'Check doors and windows for operation',
    'Check outlets and switches for visible damage',
    'Check light fixtures and ceiling fans',
    'Check trip hazards or safety concerns',
  ] },
  { room: 'Primary Bedroom', items: [
    'Check walls, ceilings, and floors for visible damage',
    'Check doors and windows for operation',
    'Check outlets and switches for visible damage',
    'Check light fixtures and ceiling fans',
    'Check smoke/CO detectors if accessible',
  ] },
  { room: 'Bedroom 2', items: [
    'Check walls, ceilings, and floors for visible damage',
    'Check doors and windows for operation',
    'Check outlets and switches for visible damage',
    'Check light fixtures and ceiling fans',
    'Check smoke/CO detectors if accessible',
  ] },
  { room: 'Bedroom 3', items: [
    'Check walls, ceilings, and floors for visible damage',
    'Check doors and windows for operation',
    'Check outlets and switches for visible damage',
    'Check light fixtures and ceiling fans',
    'Check smoke/CO detectors if accessible',
  ] },
  { room: 'Primary Bathroom', items: [
    'Check sink, toilet, tub/shower, and drains',
    'Check for active leaks or moisture concerns',
    'Check caulk, grout, walls, ceilings, and flooring',
    'Check exhaust fan or ventilation',
    'Check bathroom GFCI protection where accessible',
  ] },
  { room: 'Bathroom 2', items: [
    'Check sink, toilet, tub/shower, and drains',
    'Check for active leaks or moisture concerns',
    'Check caulk, grout, walls, ceilings, and flooring',
    'Check exhaust fan or ventilation',
    'Check bathroom GFCI protection where accessible',
  ] },
  { room: 'Laundry', items: [
    'Check washer supply and drain connections',
    'Check dryer vent material, routing, and termination',
    'Check for leaks, moisture, or floor damage',
    'Check laundry GFCI protection where accessible',
    'Check ventilation and appliance clearance',
  ] },
  { room: 'Garage', items: [
    'Check garage door operation and safety concerns',
    'Check garage walls, ceilings, and floors for damage',
    'Check outlets, switches, and fixtures for visible concerns',
    'Check storage, clearance, or access limitations',
  ] },
  { room: 'Basement / Crawlspace', items: [
    'Check moisture, staining, ventilation, and insulation',
    'Check visible structural, foundation, or framing concerns',
    'Check drainage, sump, vapor barrier, or crawlspace condition',
    'Check visible pest evidence where accessible',
    'Check storage, clearance, or access limitations',
  ] },
];

export const DRAFT_CHECKLIST_STARTER_OPTIONS: readonly DraftChecklistStarterTemplate[] = [
  {
    id: 'starter-general-maintenance-field-work',
    name: 'General Home Inspection / Home Maintenance Walkthrough',
    kind: 'inspection',
    trade: 'General Maintenance',
    description: 'Whole-home checklist for room-by-room conditions, safety items, visible maintenance needs, and homeowner-ready reporting.',
    source_kind: 'starter_inspection_checklist',
    source_id: 'starter-general-maintenance-field-work',
    source_label: 'General Home Inspection / Home Maintenance Walkthrough',
    workflow_kind: 'inspection',
    job_type: 'inspection',
    source_updated_at: null,
    group_label: 'Starter Inspection Checklists',
    rooms: DEFAULT_INSPECTION_ROOMS,
  },
  {
    id: 'starter-hvac-field-work',
    name: 'HVAC Maintenance Inspection',
    kind: 'inspection',
    trade: 'HVAC',
    description: 'HVAC maintenance checklist for equipment condition, airflow, controls, drainage, safety observations, and recommendations.',
    source_kind: 'starter_inspection_checklist',
    source_id: 'starter-hvac-field-work',
    source_label: 'HVAC Maintenance Inspection',
    workflow_kind: 'inspection',
    job_type: 'inspection',
    source_updated_at: null,
    group_label: 'Starter Inspection Checklists',
    rooms: [
      { room: 'Indoor Equipment', items: ['Model, serial number, age, and visible condition documented', 'Air filter size and condition checked', 'Thermostat operation verified', 'Blower operation, vibration, and noise checked', 'Condensate drain and overflow protection checked'] },
      { room: 'Outdoor Equipment', items: ['Condenser coil and fins checked', 'Refrigerant line insulation checked', 'Clearance around unit verified', 'Disconnect and visible wiring checked', 'Unit pad and drainage checked'] },
      { room: 'Recommendations', items: ['Temperature split or performance note recorded', 'Safety concerns documented', 'Repair or maintenance recommendation added', 'Next service interval discussed'] },
    ],
  },
  {
    id: 'starter-electrical-field-work',
    name: 'Electrical Safety Check',
    kind: 'inspection',
    trade: 'Electrical',
    description: 'Electrical safety checklist for panels, devices, GFCI/AFCI protection, visible wiring concerns, detectors, and recommendations.',
    source_kind: 'starter_inspection_checklist',
    source_id: 'starter-electrical-field-work',
    source_label: 'Electrical Safety Check',
    workflow_kind: 'inspection',
    job_type: 'inspection',
    source_updated_at: null,
    group_label: 'Starter Inspection Checklists',
    rooms: [
      { room: 'Panel and Power', items: ['Panel labeling checked', 'Breaker condition checked for heat, corrosion, or damage', 'Open knockouts or exposed wiring noted', 'Grounding and bonding visible where accessible'] },
      { room: 'Devices and Fixtures', items: ['GFCI protection tested where required', 'Switches, outlets, and fixtures checked', 'Smoke and carbon monoxide detectors noted', 'Exterior outlets and covers checked'] },
      { room: 'Repair Notes', items: ['Homeowner concern documented', 'Repair or diagnostic work completed', 'Permit or follow-up recommendation noted', 'Photos added for homeowner record'] },
    ],
  },
  {
    id: 'starter-plumbing-field-work',
    name: 'Plumbing Inspection',
    kind: 'inspection',
    trade: 'Plumbing',
    description: 'Plumbing checklist for water heaters, fixtures, supply lines, drains, leaks, shutoffs, visible moisture, and recommendations.',
    source_kind: 'starter_inspection_checklist',
    source_id: 'starter-plumbing-field-work',
    source_label: 'Plumbing Inspection',
    workflow_kind: 'inspection',
    job_type: 'inspection',
    source_updated_at: null,
    group_label: 'Starter Inspection Checklists',
    rooms: [
      { room: 'Water Heater', items: ['Tank or equipment condition checked', 'Visible leaks, corrosion, or staining noted', 'Pressure relief valve and discharge pipe checked', 'Venting, clearance, or electrical/gas safety concerns documented'] },
      { room: 'Fixtures and Supply', items: ['Faucets, toilets, and visible fixtures checked', 'Supply valves and connectors checked', 'Water pressure or flow concerns documented', 'Visible leaks or moisture at fixtures documented'] },
      { room: 'Drains and Waste', items: ['Sink, tub, shower, and floor drains checked where accessible', 'Slow drain, odor, backup, or trap concern documented', 'Visible drain piping condition checked', 'Cleanout or access limitations noted'] },
      { room: 'Recommendations', items: ['Repair recommendation added if needed', 'Urgent leak or safety concern documented', 'Preventive maintenance recommendation added', 'Photos added for homeowner record'] },
    ],
  },
  {
    id: 'starter-pest-control-field-work',
    name: 'Pest Inspection',
    kind: 'inspection',
    trade: 'Pest Control',
    description: 'Pest inspection checklist for activity evidence, entry points, moisture conditions, damage, treatment recommendations, and follow-up.',
    source_kind: 'starter_inspection_checklist',
    source_id: 'starter-pest-control-field-work',
    source_label: 'Pest Inspection',
    workflow_kind: 'inspection',
    job_type: 'inspection',
    source_updated_at: null,
    group_label: 'Starter Inspection Checklists',
    rooms: [
      { room: 'Exterior Conditions', items: ['Entry points, gaps, or penetrations checked', 'Vegetation, moisture, wood contact, or conducive conditions noted', 'Nests, trails, droppings, or visible activity documented', 'Foundation, doors, windows, and utility penetrations checked'] },
      { room: 'Interior Evidence', items: ['Droppings, damage, staining, or odor evidence documented', 'Kitchen, pantry, attic, crawlspace, or garage areas checked where accessible', 'Moisture or food-source conditions noted', 'Photos added for homeowner record'] },
      { room: 'Recommendations', items: ['Treatment or exclusion recommendation added', 'Sanitation or moisture-control recommendation added', 'Follow-up timing documented', 'Urgent structural or health concern documented'] },
    ],
  },
  {
    id: 'starter-roofing-field-work',
    name: 'Roof / Exterior Inspection',
    kind: 'inspection',
    trade: 'Roofing',
    description: 'Roof and exterior checklist for roof covering, flashing, penetrations, gutters, siding, drainage, and visible exterior concerns.',
    source_kind: 'starter_inspection_checklist',
    source_id: 'starter-roofing-field-work',
    source_label: 'Roof / Exterior Inspection',
    workflow_kind: 'inspection',
    job_type: 'inspection',
    source_updated_at: null,
    group_label: 'Starter Inspection Checklists',
    rooms: [
      { room: 'Roof Covering', items: ['Roof material and approximate condition documented', 'Missing, lifted, cracked, damaged, or deteriorated areas noted', 'Debris, moss, ponding, or surface wear documented', 'Photos added for notable roof conditions'] },
      { room: 'Flashing and Penetrations', items: ['Flashing at walls, chimney, valleys, and skylights checked', 'Pipe boots, vents, and roof penetrations checked', 'Interior leak concern connected to roof area if known', 'Urgent water-entry concern documented'] },
      { room: 'Exterior and Drainage', items: ['Gutters and downspouts checked for flow, attachment, and extensions', 'Siding, trim, fascia, soffit, and caulking concerns documented', 'Grading or drainage concern near structure noted', 'Repair or maintenance recommendation added'] },
    ],
  },
];
